back/refacto: modifie middleware sanitizer and controle admin
cod-access11/cod-access pull request #3
Opened 2021-04-13 10:19 UTC by derfy86

2021-04-13 12:55 UTC, AnnekimBanchereau approved these changes

2021-04-13 17:38 UTC, florian-sanders requested changes
code 401 en cas de refus d'accès si pas admin
middleware isAdmin dans route pour upload et association d'une image à une question

2021-04-13 17:38 UTC, florian-sanders commented on back/app/middleware/is-admin.js
> +        return res.status(400).json({
@derfy86 peut-être plutôt un code 401 ici vu que ça correspond exactement à ce cas normalement ?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2021-04-13 17:38 UTC, florian-sanders commented on back/app/router.js
> +    .post(authorizationMiddlewareNotPass, sanitizer, multerConfig.imageToQuestion);
@derfy86 je crois qu'il faut que cette route soit uniquement dispo pour les admins

2021-04-14 06:24 UTC, derfy86 commented on back/app/router.js
> +    .post(authorizationMiddlewareNotPass, sanitizer, multerConfig.imageToQuestion);
@florian-sanders je me suis aussi fait la remarque mais je n'ai pas vu de controle d'admin dans imageToQuestion du coup j'ai laissé comme c'était pour ne pas trop perturber le code dans un premier temps mais cela me semble plus logique en effet

2021-04-14 06:27 UTC, derfy86 commented on back/app/middleware/is-admin.js
> +        return res.status(400).json({
@florian-sanders sur opquast on a même vu du 403 pour accès non autorisé ... Dans mon souvenir j'avais placé des 401 sur les trois quarts j'ai du prendre le seul en 400 qui trainait. On le passe du coup en 401 merci

2021-04-14 08:32 UTC, florian-sanders approved these changes

2021-04-14 08:32 UTC, merged